char c;
unsigned char uc;
signed char sc;
short s;
unsigned short us;
signed short ss;
int i;
unsigned int ui;
signed int si;
long l;
unsigned long ul;
signed long sl;
long long ll;
unsigned long long ull;
signed long long sll;

char* cstr;
unsigned char* ustr;
signed char* sstr;
short* ps;
unsigned short* ups;
signed short* sps;
int* pi;
unsigned int* upi;
signed int* spi;
long* pl;
unsigned long* upl;
signed long* spl;
long long* pll;
unsigned long long* pull;
signed long long* psll;

char ac[];
unsigned char uac[];
short as[];
unsigned short uas[];
int ai[];
unsigned int uai[];
long al[];
unsigned long ual[];
long long all[];
unsigned long long uall[];

char sac[42];
unsigned char suac[42];
short sas[42];
unsigned short suas[42];
int sai[42];
unsigned int suai[42];
long sal[42];
unsigned long sual[42];
